[package]
name = "rucopy"
version = "0.1.0"
authors = ["Adam Gutglick <adamgsal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fibers = "0.1"
futures = "0.1"
rusoto_core = "0.41.0"
rusoto_s3 = "0.41.0"
